#%RAML 1.0

title: App manager
version: v1
baseUri: https://github.com/MikeTaylor/mod-app-manager

documentation:
  - title: mod-app-manager API
    content: This documents the API calls that can be made to fetch a list of a FOLIO system's available apps, and to manage the list of app sources.

types:
  app: !include app.json

/app-manager:
  /apps:
    get:
      description: Retrieve all available apps from all sources
      responses:
        200:
          body:
            application/json:
              type: !include apps.json
              example: !include example-apps.json
        500:
          body:
            text/plain:
              description: A brief textual description of what went wrong
    /{id}:
      get:
        description: XXX NOT SUPPORTED, here only for schema validation
        responses:
          200:
            body:
              application/json:
                type: !include app.json
                example: !include example-app.json
  /config:
    /sources:
      get:
        description: Retrieve all configured sources of apps
        responses:
          200:
            body:
              application/json:
                type: !include sources.json
                example: !include example-sources.json
      post:
        description: Create a new source from which apps can be retrieved
        body:
          application/json:
            example: !include example-source.json
            type: !include source.json
        responses:
          201:
            body:
              text/plain:
                description: The ID of the newly created record. This can be used to address the record using PUT to update it, or DELETE.
                example: a361b559-ca7c-412e-a4d0-6e4e3fb9320a
      /{id}:
        put:
          description: Update a source from which apps can be retrieved
          body:
            application/json:
              type: !include source.json
              example: !include example-source.json
          responses:
            204:
              description: Successful update
        delete:
          description: Delete an app source
          responses:
            204:
              description: Successful deletion
